# Generated by Django 6.0.2 on 2026-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0002_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='talentsstories/'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='talentvideo',
            field=models.FileField(upload_to='talentsstories/'),
        ),
    ]
