# Generated by Django 6.0.2 on 2026-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0003_talent_thumbnail_alter_talent_talentvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
