# Generated by Django 6.0.2 on 2026-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0004_registration_temp_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('story_about_person', models.TextField()),
                ('quotation', models.CharField(max_length=200)),
                ('talent', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='submissions/thumbnails/')),
                ('talentvideo', models.FileField(upload_to='submissions/videos/')),
                ('desc_of_talent', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
