# Generated by Django 6.0.2 on 2026-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0005_talentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
