# Generated by Django 6.0.2 on 2026-03-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0008_alter_contact_email_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.registration'),
        ),
        migrations.AddField(
            model_name='talentsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.registration'),
        ),
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talkshow_backend.talentrole'),
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='talkshow_backend.talent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='talkshow_backend.registration')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='talkshow_backend.registration')),
            ],
            options={
                'unique_together': {('subscriber', 'subscribed_to')},
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='talkshow_backend.talent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.registration')),
            ],
            options={
                'unique_together': {('user', 'talent_video')},
            },
        ),
    ]
