# Generated by Django 6.0.2 on 2026-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0009_talentrole_feedback_is_approved_talent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentsubmission',
            name='dismissed_by_user',
            field=models.BooleanField(default=False, help_text='User has acknowledged and dismissed this rejection'),
        ),
        migrations.AddField(
            model_name='talentsubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the user when rejected', null=True),
        ),
        migrations.AlterField(
            model_name='talentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
