# Generated by Django 6.0.2 on 2026-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0010_talentsubmission_dismissed_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='talent',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
