# Generated by Django 6.0.2 on 2026-03-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0011_alter_talent_email_alter_talent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_story', to='talkshow_backend.talentsubmission'),
        ),
    ]
