# Generated by Django 6.0.2 on 2026-03-18 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0012_talent_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_story', to='talkshow_backend.talentsubmission'),
        ),
    ]
