# Generated by Django 6.0.2 on 2026-03-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0013_alter_talent_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow')], max_length=20)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='talkshow_backend.registration')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.registration')),
                ('talent_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.talent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
