# Generated by Django 6.0.2 on 2026-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='talentsubmission',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
