# Generated by Django 6.0.2 on 2026-03-19 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0015_registration_gender_talentsubmission_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_bio_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(default=datetime.datetime(2026, 3, 19, 6, 9, 36, 334040, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
