# Generated by Django 6.0.2 on 2026-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0017_registration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talent',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
