# Generated by Django 6.0.2 on 2026-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0019_fix_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='deletion_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
