# Generated by Django 6.0.2 on 2026-03-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0020_registration_deletion_scheduled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone_number',
        ),
    ]
