# Generated by Django 6.0.2 on 2026-03-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshow_backend', '0021_remove_feedback_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile_link', to='talkshow_backend.registration'),
        ),
        migrations.AddField(
            model_name='notification',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talkshow_backend.episode'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='talkshow_backend.episode'),
        ),
        migrations.AddField(
            model_name='videolike',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='talkshow_backend.episode'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='talent_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='talkshow_backend.talent'),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='talent_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='talkshow_backend.talent'),
        ),
    ]
